### ISSUE TITLE
Crash on non empty list return.

### ISSUE THREAD

**Issue by jklmnn** [GroundApps/ShoppingList#39]
App version 1.1 crashes if the server returns a non empty list from function = listall.
The exact server output that crashes the app is: `{"type":1000,"items":[{"item":"item2","count":1}]}`.

`EDIT: Stacktrace:
    E/AndroidRuntime﹕ FATAL EXCEPTION: main
        Process: org.janb.shoppinglist, PID: 26665
        java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
                at org.janb.shoppinglist.model.ShoppingListAdapter.getView(ShoppingListAdapter.java:63)
                at android.widget.AbsListView.obtainView(AbsListView.java:2347)
                at android.widget.ListView.makeAndAddView(ListView.java:1864)
                at android.widget.ListView.fillDown(ListView.java:698)
                at android.widget.ListView.fillFromTop(ListView.java:759)
                at android.widget.ListView.layoutChildren(ListView.java:1659)
                at android.widget.AbsListView.onLayout(AbsListView.java:2151)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:562)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1009)
            at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:719)
            at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:733)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:907)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnabl`

**Comment by J-8** [comment]
The mysqli connector in line 33/34 should return an array with itemTitle and itemCount. I am sorry if I forgot that. I really have to work on the whole communicating changes thing...

**Comment by jklmnn** [comment]
I didn't test that with mysql but with sqlite. Maybe you should write a short document that explains what input and output from both, app and backend, is required. That would make it much easier to adapt the api.

**Comment by J-8** [comment]
I get home tomorrow and hopefully will have time on Sunday to do just that. I would have never thought that it would be this complicated for us:D Be we will get there;)

**Comment by jklmnn** [comment]
I tried again with the current backend version and I can't recreate the issue.
